version: '2.2'
services:
  app:
    container_name: app
    build: ./src/backend
    restart: always

    ports: 
      - 5000:5000
    volumes:
      - ./src/backend:/usr/src/app
    networks:
      default:
        aliases:
          - app
  nginx:
    image: nginx:1.14
    restart: always
    container_name: nginx
    ports:
      - 80:80
    # volumes:
    #   - /data/db_docker:/data/db
    networks:
      default:
        aliases:
          - nginx
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es_data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      default:
        aliases:
          - elasticsearch
  mongodb:
    image: mongo:3.4
    container_name: mongodb

    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb_data:/data/db
    command: mongod
    networks:
      default:
        aliases:
          - mongodb

  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro

    ports: 
     - 9000:9000

    networks:
      default:
        aliases:
          - cerebro
# volumes:
#   esdata1:
#     driver: local

