version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      default:
        aliases:
          - elasticsearch
  mongodb:
    image: mongo:3.4
    container_name: mongodb

    ports:
      - 27017:27017
    volumes:
      - /data/db_docker:/data/db
    command: mongod
    networks:
      default:
        aliases:
          - mongodb
  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro

    ports: 
     - 9000:9000

    networks:
      default:
        aliases:
          - cerebro
volumes:
  esdata1:
    driver: local

